- name: activate hardware watchdog
  lineinfile:
    dest: /boot/config.txt
    line: "dtparam=watchdog=on"
    insertafter: "^#dtparam=spi=on"

- name: Stop watchdog daemon
  systemd:
    name: watchdog.service
    state: stopped

- name: copy systemd watchdog unit to make it modifiyable
  copy:
    remote_src: true
    src: /lib/systemd/system/watchdog.service
    dest: /etc/systemd/system/
    force: no

- name: Make watchdog daemon activatable
  lineinfile:
    path: /etc/systemd/system/watchdog.service
    insertafter: '[Install]'
    line: 'WantedBy=multi-user.target'

- name: Activate watchdog daemon
  systemd:
    name: watchdog.service
    daemon_reload: yes
    enabled: True
    state: started
